apiVersion: v1
kind: Pod 
metadata: 
 name: postgres-pod
 labels:
  type: datadase
  author: mohanal
spec:
  containers: 
   - name: mydb
     image: postgres
     env: 
      - name: POSTGRES_PASSWORD
        value: mohanlal
      - name: POSTGRES_USER
        value: dbuser
      - name: POSTGRES_DB
        value: mydb    


      
